export const SHOW_SEARCH_FORM = "SHOW_SEARCH_FORM";
export const CHOOSE_DIET = "CHOOSE_DIET";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_MIN_CALORIES = "SET_MIN_CALORIES";
export const SET_MAX_CALORIES = "SET_MAX_CALORIES";
export const SET_RECEPIES = "SET_RECEPIES";
